// Code generated by MockGen. DO NOT EDIT.
// Source: tickets/internal/application/usecases/booking (interfaces: ShowsRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	shows "tickets/internal/domain/shows"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockShowsRepo is a mock of ShowsRepo interface.
type MockShowsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockShowsRepoMockRecorder
}

// MockShowsRepoMockRecorder is the mock recorder for MockShowsRepo.
type MockShowsRepoMockRecorder struct {
	mock *MockShowsRepo
}

// NewMockShowsRepo creates a new mock instance.
func NewMockShowsRepo(ctrl *gomock.Controller) *MockShowsRepo {
	mock := &MockShowsRepo{ctrl: ctrl}
	mock.recorder = &MockShowsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockShowsRepo) EXPECT() *MockShowsRepoMockRecorder {
	return m.recorder
}

// GetShow mocks base method.
func (m *MockShowsRepo) GetShow(arg0 context.Context, arg1 uuid.UUID) (*shows.Show, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShow", arg0, arg1)
	ret0, _ := ret[0].(*shows.Show)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShow indicates an expected call of GetShow.
func (mr *MockShowsRepoMockRecorder) GetShow(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShow", reflect.TypeOf((*MockShowsRepo)(nil).GetShow), arg0, arg1)
}
