// Code generated by MockGen. DO NOT EDIT.
// Source: tickets/internal/application/usecases/booking (interfaces: BookingsRepo)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	entities "tickets/internal/entities"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
)

// MockBookingsRepo is a mock of BookingsRepo interface.
type MockBookingsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBookingsRepoMockRecorder
}

// MockBookingsRepoMockRecorder is the mock recorder for MockBookingsRepo.
type MockBookingsRepoMockRecorder struct {
	mock *MockBookingsRepo
}

// NewMockBookingsRepo creates a new mock instance.
func NewMockBookingsRepo(ctrl *gomock.Controller) *MockBookingsRepo {
	mock := &MockBookingsRepo{ctrl: ctrl}
	mock.recorder = &MockBookingsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookingsRepo) EXPECT() *MockBookingsRepoMockRecorder {
	return m.recorder
}

// CreateBooking mocks base method.
func (m *MockBookingsRepo) CreateBooking(arg0 context.Context, arg1 entities.Booking) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateBooking", arg0, arg1)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateBooking indicates an expected call of CreateBooking.
func (mr *MockBookingsRepoMockRecorder) CreateBooking(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateBooking", reflect.TypeOf((*MockBookingsRepo)(nil).CreateBooking), arg0, arg1)
}

// GetBookingsCountByShowID mocks base method.
func (m *MockBookingsRepo) GetBookingsCountByShowID(arg0 context.Context, arg1 uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBookingsCountByShowID", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBookingsCountByShowID indicates an expected call of GetBookingsCountByShowID.
func (mr *MockBookingsRepoMockRecorder) GetBookingsCountByShowID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBookingsCountByShowID", reflect.TypeOf((*MockBookingsRepo)(nil).GetBookingsCountByShowID), arg0, arg1)
}
