version: '3'

tasks:
  app:
    cmds:
      - go run main.go
    env:
      REDIS_ADDR: localhost:6379
      GATEWAY_ADDR: http://localhost:8888

  local-test-deps:
    cmds:
      - docker-compose up -d

  test-all:
    cmds:
      - go test ./... -v
    env:
      REDIS_ADDR: localhost:6379

  test-component:
    cmds:
      - go test ./tests/ -v
    env:
      REDIS_ADDR: localhost:6379
      POSTGRES_URL: postgres://user:password@localhost:5432/db?sslmode=disable
#    GATEWAY_ADDR=http://localhost:8888;

